# Generated by Django 3.2 on 2022-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221127_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/defAv.jpg', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
